name: Docker Image

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    # Runs "every Monday" (see https://crontab.guru)
    - cron: '0 0 * * MON'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: set lower case owner name
      #   run: |
      #     echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
      #   env:
      #     OWNER: '${{ github.repository_owner }}'
      - uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to DockerHub Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/derper:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/derper:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/derper:${{ github.sha }}
